// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAcDpr9xBNrkts0NtInFSU57qgIWp-O5jg',
    appId: '1:135041680434:web:f879367965a6e53bd9e82b',
    messagingSenderId: '135041680434',
    projectId: 'device-streaming-2258116d',
    authDomain: 'device-streaming-2258116d.firebaseapp.com',
    storageBucket: 'device-streaming-2258116d.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyANiwawuJjBAG5MqOeY4RlGdLyZB2S_GJk',
    appId: '1:135041680434:android:23b330cdfadd516ed9e82b',
    messagingSenderId: '135041680434',
    projectId: 'device-streaming-2258116d',
    storageBucket: 'device-streaming-2258116d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBF-b4gr3a0gjpXxDm5FurPWiPYAlRNTL8',
    appId: '1:135041680434:ios:2bb9233bdab7e066d9e82b',
    messagingSenderId: '135041680434',
    projectId: 'device-streaming-2258116d',
    storageBucket: 'device-streaming-2258116d.firebasestorage.app',
    iosBundleId: 'com.example.portfolio',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBF-b4gr3a0gjpXxDm5FurPWiPYAlRNTL8',
    appId: '1:135041680434:ios:2bb9233bdab7e066d9e82b',
    messagingSenderId: '135041680434',
    projectId: 'device-streaming-2258116d',
    storageBucket: 'device-streaming-2258116d.firebasestorage.app',
    iosBundleId: 'com.example.portfolio',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAcDpr9xBNrkts0NtInFSU57qgIWp-O5jg',
    appId: '1:135041680434:web:e2f0352c979ff2ded9e82b',
    messagingSenderId: '135041680434',
    projectId: 'device-streaming-2258116d',
    authDomain: 'device-streaming-2258116d.firebaseapp.com',
    storageBucket: 'device-streaming-2258116d.firebasestorage.app',
  );

}